---
- name: Install Goss and run Windows 2019 CIS Audit
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Chocolatey (if not installed)
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present
        
    - name: Ensure Git is in the system PATH
      win_shell: |
        $env:Path += ";C:\Program Files\Git\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Download Goss binary
      win_get_url:
        url: https://github.com/goss-org/goss/releases/download/v0.4.7/goss-windows-amd64.exe
        dest: C:\goss.exe

    - name: Ensure Goss binary is executable
      win_command:
        cmd: powershell.exe -Command "Set-ExecutionPolicy Bypass -Scope Process -Force;"

    - name: Clone the ansible-lockdown Windows 2019 CIS Audit repository
      win_shell: |
        if (-not (Test-Path -Path "C:\audit")) {
          git clone https://github.com/ansible-lockdown/Windows-2019-CIS-Audit.git C:\audit
        }
      args:
        creates: C:\audit

    - name: Ensure Goss is installed
      win_command:
        cmd: C:\goss.exe --version
      register: goss_version

    - name: Check if Goss is installed
      debug:
        msg: "Goss version: {{ goss_version.stdout }}"

    - name: Run Goss audit
      win_shell: |
        Set-Location -Path C:\audit
        C:\goss.exe -g windows-2019-cis.goss.yaml v
      args:
        chdir: C:\audit
      register: goss_audit

    - name: Show Goss audit results
      debug:
        msg: "{{ goss_audit.stdout }}"
