---
- name: Install Goss and run Windows 2019 CIS Audit
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Chocolatey (if not installed)
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present
        
    - name: Ensure Git is in the system PATH
      win_shell: |
        $env:Path += ";C:\Program Files\Git\bin"
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

    - name: Create directory for Goss
      win_file:
        path: C:\remediation_audit_logs
        state: directory
        
    - name: Download Goss binary
      win_get_url:
        url: https://github.com/goss-org/goss/releases/download/v0.4.7/goss-windows-amd64.exe
        dest: C:\remediation_audit_logs\goss.exe

    - name: Ensure Goss binary is executable
      win_command:
        cmd: powershell.exe -Command "Set-ExecutionPolicy Bypass -Scope Process -Force;"
        
    - name: Clone the ansible-lockdown Windows 2019 CIS Audit repository
      win_shell: |
        if (-not (Test-Path -Path "C:\remediation_audit_logs\Windows-2019-CIS-Audit")) {
          & 'C:\Program Files\Git\bin\git.exe' clone https://github.com/alfiilham/Windows-2019-CIS-Audit.git C:\remediation_audit_logs\Windows-2019-CIS-Audit
        }
      args:
        creates: C:\remediation_audit_logs\Windows-2019-CIS-Audit

    - name: Ensure Goss is installed
      win_command:
        cmd: C:\remediation_audit_logs\goss.exe --version
      register: goss_version

    - name: Check if Goss is installed
      debug:
        msg: "Goss version: {{ goss_version.stdout }}"

    - name: Run Goss audit using run_audit.ps1
      win_shell: |
        $env:GOSS_USE_ALPHA=1
        Set-Location -Path C:\remediation_audit_logs\Windows-2019-CIS-Audit
        & .\run_audit.ps1
      args:
        chdir: C:\remediation_audit_logs\Windows-2019-CIS-Audit
      register: goss_audit

    - name: Show Goss audit results
      debug:
        msg: "{{ goss_audit.stdout }}"

    - name: Find the latest JSON file
      win_find:
        paths: C:\remediation_audit_logs
        recurse: no
        patterns: '*.json'
        age: 1d
      register: json_files

    - name: Set fact for the latest JSON file
      set_fact:
        latest_json_file: "{{ json_files.files | sort(attribute='mtime', reverse=True) | first }}"

    - name: Copy the latest JSON file to control machine
      win_copy:
        src: "{{ latest_json_file.path }}"
        dest: "/tmp/{{ latest_json_file.path | basename }}"
      when: latest_json_file is defined

    - name: Copy the JSON file to the Linux server
      copy:
        src: "/tmp/{{ latest_json_file.path | basename }}"
        dest: "/var/www/html/"
      delegate_to: 10.8.230.36
      vars:
        ansible_ssh_pass: "P@ssw0rd"
