---
- name: Audit
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    remote_server: "10.100.11.14"
    remote_path: "/var/www/html"
    remote_user: "root"
    remote_password: "p@ssw0rd"

  tasks:
    - name: Ensure required packages are installed
      yum:
        name: 
          - openscap-scanner
          - scap-security-guide
          - sshpass
        state: present
      register: install_packages
      failed_when: install_packages.failed > 0

    - name: Run oscap scan
      command: >
        oscap xccdf eval
        --profile {{ profile }}
        --results-arf results.xml
        --report {{ ansible_default_ipv4.address }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      ignore_errors: yes

    - name: Copy the report to the remote server
      ansible.builtin.shell: |
        sshpass -p '{{ remote_password }}' scp -o StrictHostKeyChecking=no {{ ansible_default_ipv4.address }}.html {{ remote_user }}@{{ remote_server }}:{{ remote_path }}
