---
- name: Install Goss and run Windows 2019 CIS Audit
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Chocolatey (if not installed)
      community.windows.win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      community.windows.win_chocolatey:
        name: git
        state: present

    - name: Install Goss using Chocolatey
      community.windows.win_chocolatey:
        name: goss
        state: present

    - name: Clone the ansible-lockdown Windows 2019 CIS Audit repository
      ansible.windows.win_shell: |
        if (-not (Test-Path -Path "C:\audit")) {
          git clone https://github.com/ansible-lockdown/Windows-2019-CIS-Audit.git C:\audit
        }
      args:
        creates: C:\audit

    - name: Ensure Goss is installed
      ansible.windows.win_command: goss --version
      register: goss_version

    - name: Check if Goss is installed
      ansible.windows.win_debug:
        msg: "Goss version: {{ goss_version.stdout }}"

    - name: Run Goss audit
      ansible.windows.win_shell: |
        Set-Location -Path C:\audit
        goss -g windows-2019-cis.goss.yaml v
      args:
        chdir: C:\audit
      register: goss_audit

    - name: Show Goss audit results
      ansible.windows.win_debug:
        msg: "{{ goss_audit.stdout }}"
