---
- name: Download, install goss and gost, audit and copy result JSON file
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    remote_server: "10.8.230.36"
    remote_path: "/var/www/html"
    remote_user: "root"
    remote_password: "P@ssw0rd"
    local_path: "/tmp"
    audit_dir: "C:\\path\\to\\audit-files"
    goss_url: "https://github.com/aelsabbahy/goss/releases/download/v0.3.6/goss-windows-amd64.exe
  roles:
    - role: Windows-2019-CIS
      tags:
        - level1-memberserver
  tasks:
    - name: Download goss
      ansible.builtin.win_get_url:
        url: "{{ goss_url }}"
        dest: "C:\\Program Files\\goss.exe"

    - name: Ensure goss is executable
      ansible.builtin.win_command: |
        icacls "C:\\Program Files\\goss.exe" /grant Everyone:F

    - name: Find the latest JSON file
      ansible.builtin.win_find:
        paths: "{{ audit_dir }}"
        patterns: "*.json"
        recurse: yes
      register: found_files

    - name: Set the path to the latest JSON file
      set_fact:
        latest_json_file: "{{ found_files.files | sort(attribute='mtime', reverse=true) | first | default({}) }}"

    - name: Ensure the latest JSON file is found
      ansible.builtin.assert:
        that:
          - latest_json_file.path is defined
        fail_msg: "No JSON files found in the directory {{ audit_dir }}"

    - name: Fetch the latest audit result JSON file from the Windows managed node
      ansible.builtin.win_copy:
        src: "{{ latest_json_file.path }}"
        dest: "{{ local_path }}\\audit-result.json"
      when: latest_json_file.path is defined
      register: fetch_result

    - name: Copy the JSON file to the remote server
      ansible.builtin.shell: |
        sshpass -p '{{ remote_password }}' scp -o StrictHostKeyChecking=no "{{ fetch_result.dest }}" {{ remote_user }}@{{ remote_server }}:{{ remote_path }}/audit-result.json
      delegate_to: localhost
      when: fetch_result is defined
