---
- name: List all running services on Linux
  hosts: all
  become: yes  # Ensure the playbook runs with root privileges
  tasks:
    - name: Get the list of running services
      shell: |
        systemctl list-units --type=service --state=running
      register: running_services

    - name: Print the list of running services
      debug:
        var: running_services.stdout
