---
- name: Apply WIN Server 2019 CIS Hardening
  hosts: all
  vars:
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
    ansible_shell_type: powershell
  roles:
    - role: Windows-2019-CIS
