---
- name: Apply WIN Server 2019 CIS Hardening
  hosts: all
  vars:
    ansible_user: "administrator"
    ansible_password: "P@ssw0rd"
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
    ansible_shell_type: powershell
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
  roles:
    - role: Windows-2019-CIS
