---
- name: Apply RHEL 8 CIS Hardening and Run Audit
  hosts: all
  become: yes

  roles:
    - role: RHEL8-CIS
      vars:
        rhel8cis_section1: true
        rhel8cis_section2: true
        rhel8cis_section3: true
        rhel8cis_section4: true
        rhel8cis_section5: true
        rhel8cis_section6: true
