---
- name: Apply RHEL 8 CIS Hardening and Run Audit
  hosts: all
  become: yes

  roles:
    - role: RHEL8-CIS
      vars:
        {{result}}

  post_tasks:
    - name: Run RHEL8-CIS-Audit
      include_role:
        name: RHEL8-CIS-Audit
