---
- name: Apply RHEL 8 CIS Hardening and Run Audit
  hosts: all
  become: yes

  roles:
    - role: RHEL8-CIS
      vars:
        rhel8cis_section1: "{{ 'rhel8cis_section1: true' in result }}"
        rhel8cis_section2: "{{ 'rhel8cis_section2: true' in result }}"
        rhel8cis_section3: "{{ 'rhel8cis_section3: true' in result }}"
        rhel8cis_section4: "{{ 'rhel8cis_section4: true' in result }}"
        rhel8cis_section5: "{{ 'rhel8cis_section5: true' in result }}"
        rhel8cis_section6: "{{ 'rhel8cis_section6: true' in result }}"
      tags:
        - level2-workstation
