---
- name: RHEL8-CIS
  src: https://github.com/ansible-lockdown/RHEL8-CIS.git
  version: devel

- name: Windows-2019-CIS
  src: https://github.com/ansible-lockdown/Windows-2019-CIS.git
  version: devel

- name: RHEL8-CIS-Audit
  src: https://github.com/ansible-lockdown/RHEL8-CIS-Audit.git
  version: devel

- name: CENTOS8-CIS-Remediate
  src: https://github.com/gerwwr/ansible-cis-centos8.git
  version: master
